-- Registro multi-tenant: NO-OP a proposito (sin DDL).
--
-- Las tablas de esta feature (organizations, profiles, subscriptions, usage_counters) NO se crean
-- desde estas migraciones: YA existen en Supabase y son la fuente de verdad. Este archivo solo
-- mantiene la convencion de una migracion por feature (V001..V004) y DOCUMENTA las columnas de las
-- que depende el backend (apps/backend/src/registration/registration-repository.ts), para detectar
-- de un vistazo cualquier desalineacion con el esquema real.
--
-- NO agregar create/alter table aqui: duplicaria objetos administrados en Supabase. Si el esquema
-- cambia, se ajusta alla y se actualiza esta nota.
--
-- Esquema esperado por el repo:
--
--   organizations
--     id           uuid pk default gen_random_uuid()
--     name         text not null
--     status       text not null default 'pending'   -- 'pending' | 'approved'
--     approved_at  timestamptz null
--     created_at   timestamptz not null default now()
--     updated_at   timestamptz not null default now()
--
--   profiles
--     id                uuid pk            -- = auth.users.id = sub del JWT
--     org_id            uuid null references organizations(id)
--     account_type      text not null      -- 'individual' | 'empresa_member'
--     role              text not null      -- 'individual' | 'org_admin'
--     full_name         text not null
--     identity_verified boolean not null default false
--     created_at        timestamptz not null default now()
--     updated_at        timestamptz not null default now()
--
--   subscriptions
--     id          uuid pk default gen_random_uuid()
--     profile_id  uuid not null references profiles(id)
--     plan        text not null      -- 'free'
--     status      text not null default 'active'
--     created_at  timestamptz not null default now()
--
--   usage_counters
--     id           uuid pk default gen_random_uuid()
--     profile_id   uuid not null references profiles(id)
--     runs_used    integer not null default 0
--     runs_limit   integer not null default 10
--     period_kind  text not null      -- 'lifetime'
--     created_at   timestamptz not null default now()
